app/expenses/urls.py
from django.urls import path

from .ajax_views import load_expenses_chart_data, load_total_expenses_chart_data
from .views import ExpensesListView, ExpensesCreateView, ExpensesDetailView, ExpensesUpdateView, ExpensesDeleteView

app_name = "expenses"

ui_patterns = [
    path('', ExpensesListView.as_view(), name='list'),
    path('create/', ExpensesCreateView.as_view(), name='create'),
    path('details/<str:expense_id>/', ExpensesDetailView.as_view(), name='details'),
    path('update/<str:expense_id>/', ExpensesUpdateView.as_view(), name='update'),
    path('delete/<str:expense_id>/', ExpensesDeleteView.as_view(), name='delete'),
]


api_patterns = [
    path('chart-data/', load_expenses_chart_data, name='expenses_chart_data'),
    path("chart-data/total/", load_total_expenses_chart_data, name="total_income_chart_data")
]

urlpatterns = ui_patterns + api_patterns

app/income/urls.py
from django.urls import path

from .views import IncomeListView, IncomeCreateView, IncomeDetailView, IncomeUpdateView, IncomeDeleteView
from .ajax_views import load_income_chart_data, load_total_income_chart_data

app_name = "income"

ui_patterns = [
    path('', IncomeListView.as_view(), name='list'),
    path('create/', IncomeCreateView.as_view(), name='create'),
    path('details/<str:income_id>/', IncomeDetailView.as_view(), name='details'),
    path('update/<str:income_id>/', IncomeUpdateView.as_view(), name='update'),
    path('delete/<str:income_id>/', IncomeDeleteView.as_view(), name='delete'),
]

api_patterns = [
    path("chart-data/", load_income_chart_data, name="income_chart_data"),
    path("chart-data/total/", load_total_income_chart_data, name="total_income_chart_data")
]

urlpatterns = ui_patterns + api_patterns

app/overview/urls.py
from django.urls import path

from app.overview.views import Overview

app_name = 'overview'

urlpatterns = [
    path('', Overview.as_view(), name='dashboard'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from app.auths.views import SignUpView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path("income/", include("app.income.urls"), name="income"),
    path("expenses/", include("app.expenses.urls"), name="expenses"),
    path("overview/", include("app.overview.urls"), name="overview"),
    path("login/", auth_views.LoginView.as_view(template_name="auth/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}PocketFlow{% endblock %}</title>
    {% include 'head/css.html' %}
    {% include 'head/thirdparties.html' %}
</head>
<body class="bg-gray-900">
<div class="flex justify-center">
    <div class="max-w-[40rem] w-full bg-white relative">
        <header class="h-14 flex justify-between items-center px-4 fixed left-0 right-0 bg-white max-w-[40rem] mx-auto border-b z-50">
            <div class="flex gap-2">
                <a href="#">
                    <img src="{% static 'images/common/logo.png' %}" width="100" alt="logo">
                </a>
            </div>

            <div class="flex items-center">
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="font-semibold text-primary hover:text-primaryHover"
                            type="submit">
                        Logout
                    </button>
                </form>
                <!--                <button class="text-primary">-->
                <!--                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" height="30" viewBox="0 0 24 24"-->
                <!--                         stroke-width="2.5"-->
                <!--                         stroke="currentColor" class="size-6">-->
                <!--                        <path stroke-linecap="round" stroke-linejoin="round"-->
                <!--                              d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"/>-->
                <!--                    </svg>-->
                <!--                </button>-->
            </div>
        </header>

        <main class="flex flex-col gap-2 py-16 min-h-screen">
            {% block content %}{% endblock %}
        </main>

        <nav class="fixed bottom-0 left-0 right-0 bg-white border-t h-14 flex max-w-[40rem] mx-auto w-full shadow">
            <a href="{% url 'overview:dashboard' %}"
               class="h-full w-1/3 hover:bg-gray-200 duration-500 flex items-center justify-center
                {% if request.resolver_match.app_name == 'overview' %}
                    bg-gray-200 text-primary pointer-events-none
                {% else %}
                    bg-white
                    cursor-pointer
                {% endif %}"
            >
                Overview
            </a>

            <a href="{% url 'income:list' %}"
               class="h-full w-1/3 hover:bg-gray-200 duration-500 flex items-center justify-center
                {% if request.resolver_match.app_name == 'income' %}
                    bg-gray-200 text-primary pointer-events-none
                {% else %}
                    bg-white
                    cursor-pointer
                {% endif %}"
            >
                Income
            </a>

            <a href="{% url 'expenses:list' %}"
               class="h-full w-1/3 hover:bg-gray-200 duration-500 flex items-center justify-center
                {% if request.resolver_match.app_name == 'expenses' %}
                    bg-gray-200 text-primary pointer-events-none
                {% else %}
                    bg-white
                    cursor-pointer
                {% endif %}"
            >
                Expenses
            </a>
        </nav>
    </div>
</div>
</body>
</html>

templates/home.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}PocketFlow{% endblock %}</title>
    {% include 'head/css.html' %}
    {% include 'head/thirdparties.html' %}
</head>
<body>
<div class="bg-white flex flex-col">
    <div class="relative isolate overflow-hidden bg-linear-to-b from-indigo-100/20">
        <div class="mx-auto max-w-7xl pt-10 pb-24 sm:pb-32 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:px-8 lg:py-40">
            <div class="px-6 lg:px-0 lg:pt-4">
                <div class="mx-auto max-w-2xl">
                    <div class="max-w-lg">
                        <img class="h-11"
                             src="{% static 'images/common/logo.png' %}"
                             alt="Pocketflow">
                        <h1 class="mt-10 text-5xl font-semibold tracking-tight text-pretty text-gray-900 sm:text-7xl">
                            PocketFlow — Take Control of Your Finances
                        </h1>
                        <p class="mt-8 text-lg font-medium text-pretty text-gray-500 sm:text-xl/8">
                            Track your income and expenses with ease. PocketFlow is your personal finance dashboard,
                            designed to help you manage money smarter. Visualize cash flow, categorize transactions, and
                            stay on top of your financial goals — all in one place.
                        </p>
                        <div class="mt-10 flex items-center gap-x-6">
                            <a href="{% url 'login' %}"
                               class="rounded-md duration-300 bg-primary px-8 py-3 text-sm font-semibold text-white shadow-xs hover:bg-primaryHover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primaryHover">
                                Get started
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-20 sm:mt-24 md:mx-auto md:max-w-2xl lg:mx-0 lg:mt-0 lg:w-screen">
                <div class="absolute inset-y-0 right-1/2 -z-10 -mr-10 w-[200%] skew-x-[-30deg] bg-white shadow-xl ring-1 shadow-indigo-600/10 ring-indigo-50 md:-mr-20 lg:-mr-36"
                     aria-hidden="true"></div>
                <div class="shadow-lg md:rounded-3xl">
                    <div class="[clip-path:inset(0)] md:[clip-path:inset(0_round_var(--radius-3xl))]">
                        <img src="{% static '/images/common/system.png' %}" class="w-full" loading="lazy">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>